"""yt-dlp cookie 副本回归测试。

锁定一个真实踩过的坑：``yt-dlp --cookies <file>`` 会**原地重写** cookie 文件
（剥掉 ``#HttpOnly_`` 前缀、把首行换成自己的签名头、丢弃不认识的字段）。
抖音导出的 62 条 cookie 会被重写成 58 条 —— 静默丢数据，且每次解析都发生一次。

修法：交给 yt-dlp 的永远是 work_dir 下的**临时副本**，生产文件只读。
这组测试保证那个行为不会退化。
"""
from __future__ import annotations

from pathlib import Path

from src.video.acquire import (
    _YTDLP_COOKIE_COPY_PREFIX,
    _ytdlp_cookie_copies,
    ytdlp_cookie_args,
)

SAMPLE = (
    "# Netscape HTTP Cookie File\n"
    "# This file was generated by Cookie Editor\n"
    "\n"
    "#HttpOnly_.douyin.com\tTRUE\t/\tTRUE\t1824644506\tsessionid\tabc123\n"
    ".douyin.com\tTRUE\t/\tTRUE\t1824644506\tsessionid_ss\tabc123\n"
    ".douyin.com\tTRUE\t/\tTRUE\t1824644506\tttwid\tttw-xyz\n"
    ".iesdouyin.com\tTRUE\t/\tTRUE\t1824644506\todin_tt\todin-abc\n"
)


def _write_sample(tmp_path: Path) -> Path:
    f = tmp_path / "cookies_douyin.txt"
    f.write_text(SAMPLE, encoding="utf-8")
    return f


def test_copies_cookie_file_and_never_hands_production_path(tmp_path: Path) -> None:
    _ytdlp_cookie_copies.clear()
    real = _write_sample(tmp_path)
    work = tmp_path / "work"

    args = ytdlp_cookie_args(real, work)

    assert args[0] == "--cookies"
    handed = Path(args[1])
    # 关键断言：交给 yt-dlp 的不是生产文件
    assert handed != real
    assert handed.is_file()
    assert handed.name.startswith(_YTDLP_COOKIE_COPY_PREFIX)
    # 副本内容与原文件逐字节相同
    assert handed.read_bytes() == real.read_bytes()
    # 生产文件内容未被触碰
    assert real.read_text(encoding="utf-8") == SAMPLE


def test_copy_is_cached_and_reused_within_task(tmp_path: Path) -> None:
    _ytdlp_cookie_copies.clear()
    real = _write_sample(tmp_path)
    work = tmp_path / "work"

    first = ytdlp_cookie_args(real, work)[1]
    second = ytdlp_cookie_args(real, work)[1]

    # 同一次任务内多次调用只拷一份（按 size+mtime 缓存）
    assert first == second
    assert len(list(work.glob(f"{_YTDLP_COOKIE_COPY_PREFIX}*"))) == 1


def test_cache_invalidated_when_source_changes(tmp_path: Path) -> None:
    _ytdlp_cookie_copies.clear()
    real = _write_sample(tmp_path)
    work = tmp_path / "work"

    first = ytdlp_cookie_args(real, work)[1]

    # 改内容后 size 变化 → 必须重新拷贝，不能用旧副本
    real.write_text(SAMPLE + ".douyin.com\tTRUE\t/\tTRUE\t1824644506\tpassport_csrf_token\tpcs\n", encoding="utf-8")
    second = ytdlp_cookie_args(real, work)[1]

    assert second != first
    assert "passport_csrf_token" in Path(second).read_text(encoding="utf-8")


def test_simulation_shows_production_file_survives_ytdlp_rewrite(tmp_path: Path) -> None:
    """模拟 yt-dlp 的原地面重写行为，证明生产文件不受影响。"""
    _ytdlp_cookie_copies.clear()
    real = _write_sample(tmp_path)
    work = tmp_path / "work"
    before = real.read_bytes()

    handed = Path(ytdlp_cookie_args(real, work)[1])
    # 复刻 yt-dlp 的破坏性行为：重写**它拿到的那份**
    handed.write_text(
        "# Netscape HTTP Cookie File\n"
        "# This file is generated by yt-dlp.  Do not edit.\n"
        "\n"
        ".douyin.com\tTRUE\t/\tTRUE\t1824644506\tsessionid\tabc123\n",
        encoding="utf-8",
    )

    # 生产文件必须一字未改
    assert real.read_bytes() == before
    assert "#HttpOnly_" in real.read_text(encoding="utf-8")


def test_missing_cookie_file_yields_no_args(tmp_path: Path) -> None:
    _ytdlp_cookie_copies.clear()
    assert ytdlp_cookie_args(None, tmp_path) == []
    assert ytdlp_cookie_args(tmp_path / "nope.txt", tmp_path) == []
